name: Deploy Frontend to GitHub Pages
run-name: Deploy ${{ inputs.branch || github.ref_name }} to [${{ inputs.environment || 'dev' }}]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
      branch:
        description: "Branch to deploy"
        required: false
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Build Docker and Deploy
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment || 'dev' }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch || github.ref_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker image with Dynamic Environment Variables
        env:
          VARS_JSON: ${{ toJson(vars) }}
          SECRETS_JSON: ${{ toJson(secrets) }}
        run: |
          echo "$VARS_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"' > .env
          echo "$SECRETS_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> .env
          echo "VITE_BASE_PATH=/${{ github.event.repository.name }}/" >> .env
          docker build --secret id=env,src=.env -t events-planner-web:github-pages .

      - name: Extract build files from Docker container
        run: |
          mkdir -p ./dist
          CONTAINER_ID=$(docker create events-planner-web:github-pages)
          docker cp $CONTAINER_ID:/usr/share/nginx/html/. ./dist/
          docker rm $CONTAINER_ID

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v6

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5